name: CI/CD

on:
  push:
    branches: [ aws_cicd, main, master ]
  pull_request:
    branches: [ aws_cicd, main, master ]
  # permet de déclencher manuellement le workflow depuis l'interface Actions
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build (si présent)
        run: npm run build --if-present

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build

  docker-build-and-push:
    name: Build and push Docker image
    needs: test
    runs-on: ubuntu-latest
    # ne pousse l'image que sur branches de déploiement (aws_cicd, main, master)
    if: github.ref == 'refs/heads/aws_cicd' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase owner
        # convertit github.repository_owner en minuscules (compatible avec GHCR)
        run: |
          echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # IMPORTANT: utiliser la variable env OWNER_LOWER (définie ci-dessus) pour éviter l'erreur de casse
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/elden-ring-website:latest
            ghcr.io/${{ env.OWNER_LOWER }}/elden-ring-website:${{ github.sha }}
          file: ./Dockerfile
          build-args: |
            NODE_ENV=production

  deploy:
    name: Deploy to Google App Engine
    needs: test
    runs-on: ubuntu-latest
    # déploiement App Engine depuis main, master, aws_cicd ou via exécution manuelle
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/aws_cicd'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check required secrets (do not fail CI, set SKIP_DEPLOY)
        run: |
          skip=false
          missing=""
          if [ -z "${{ secrets.DOTENV }}" ]; then missing="${missing} DOTENV"; skip=true; fi
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then missing="${missing} GCP_SA_KEY"; skip=true; fi
          if [ -z "${{ secrets.GCP_PROJECT }}" ]; then missing="${missing} GCP_PROJECT"; skip=true; fi
          if [ "$skip" = true ]; then
            echo "Missing required secrets:${missing}" >&2
            echo "SKIP_DEPLOY=true" >> $GITHUB_ENV
          else
            echo "SKIP_DEPLOY=false" >> $GITHUB_ENV
          fi

      - name: Create .env from secret
        if: ${{ env.SKIP_DEPLOY != 'true' }}
        run: |
          printf '%s' "${{ secrets.DOTENV }}" > .env
          echo ".env created with secrets.DOTENV (masked)."

      - name: Install dependencies and build frontend+server
        if: ${{ env.SKIP_DEPLOY != 'true' }}
        run: |
          npm ci
          npm run build
          npm run build:server

      - name: Install gcloud SDK
        if: ${{ env.SKIP_DEPLOY != 'true' }}
        uses: google-github-actions/setup-gcloud@v1
        with:
          # installe la dernière version du SDK
          version: 'latest'

      - name: Write GCP service account key to file
        if: ${{ env.SKIP_DEPLOY != 'true' }}
        run: |
          # écrire la clé JSON dans un fichier sécurisé en préservant les retours à la ligne
          # et en supprimant les CR éventuels (Windows)
          printf '%s' "${{ secrets.GCP_SA_KEY }}" | tr -d '\r' > "$RUNNER_TEMP/gcp-key.json"
          chmod 600 "$RUNNER_TEMP/gcp-key.json"
          echo "GCP_KEY_PATH=$RUNNER_TEMP/gcp-key.json" >> $GITHUB_ENV

          # validation basique du JSON pour échouer vite si la clé est mal formée
          if ! python -c "import sys, json; json.load(open('$RUNNER_TEMP/gcp-key.json'))" >/dev/null 2>&1; then
            echo "ERROR: GCP_SA_KEY secret does not contain valid JSON" >&2
            echo "You should verify the secret contents in Settings → Secrets and variables → Actions" >&2
            exit 1
          fi

      - name: Authenticate to GCP (activate service account) and set project
        if: ${{ env.SKIP_DEPLOY != 'true' }}
        env:
          GCP_KEY_PATH: ${{ env.GCP_KEY_PATH }}
        run: |
          # active le compte de service explicitement et définit le projet
          gcloud auth activate-service-account --key-file="$GCP_KEY_PATH"
          gcloud config set project "${{ secrets.GCP_PROJECT }}"

      - name: Deploy to App Engine
        if: ${{ env.SKIP_DEPLOY != 'true' }}
        run: |
          gcloud app deploy --quiet

      - name: Skip deploy message
        if: ${{ env.SKIP_DEPLOY == 'true' }}
        run: |
          echo "Skipping Google App Engine deploy because required secrets are missing:"
          echo " - DOTENV (secret DOTENV)"
          echo " - GCP_SA_KEY (service account JSON)"
          echo " - GCP_PROJECT (project id)"
          echo "Add them in Settings → Secrets and Variables → Actions, then re-run the workflow."
