name: CI/CD

on:
  push:
    branches: [ aws_cicd, main, master ]
  pull_request:
    branches: [ aws_cicd, main, master ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build (si présent)
        run: npm run build --if-present

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build

  docker-build-and-push:
    name: Build and push Docker image
    needs: test
    runs-on: ubuntu-latest
    # ne pousse l'image que sur branches de déploiement (aws_cicd, main, master)
    if: github.ref == 'refs/heads/aws_cicd' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase owner
        # convertit github.repository_owner en minuscules (compatible avec GHCR)
        run: |
          echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # IMPORTANT: utiliser la variable env OWNER_LOWER (définie ci-dessus) pour éviter l'erreur de casse
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/elden-ring-website:latest
            ghcr.io/${{ env.OWNER_LOWER }}/elden-ring-website:${{ github.sha }}
          file: ./Dockerfile
          build-args: |
            NODE_ENV=production

  deploy:
    name: Deploy to Google App Engine
    needs: test
    runs-on: ubuntu-latest
    # déploiement App Engine uniquement depuis main ou master
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check required secrets
        # échoue si DOTENV, GCP_SA_KEY ou GCP_PROJECT sont manquants
        run: |
          if [ -z "${{ secrets.DOTENV }}" ]; then
            echo "ERROR: secret DOTENV is not set" >&2
            exit 1
          fi
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "ERROR: secret GCP_SA_KEY is not set" >&2
            exit 1
          fi
          if [ -z "${{ secrets.GCP_PROJECT }}" ]; then
            echo "ERROR: secret GCP_PROJECT is not set" >&2
            exit 1
          fi
          echo "All required secrets are present."

      - name: Create .env from secret
        # Assurez-vous d'ajouter le secret DOTENV dans les Settings > Secrets
        run: |
          printf '%s' "${{ secrets.DOTENV }}" > .env
          echo ".env created with secrets.DOTENV (masked)."

      - name: Install dependencies and build frontend+server
        run: |
          npm ci
          npm run build
          npm run build:server

      - name: Set up gcloud (authenticate)
        uses: google-github-actions/setup-gcloud@v1
        with:
          # secrets.GCP_SA_KEY doit contenir la clé JSON du service account
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet
