name: CI/CD

on:
  push:
    branches: [ aws_cicd, master ]
  pull_request:
    branches: [ aws_cicd, master ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (si présent)
        run: npm run lint --if-present

      - name: Test
        run: npm test

      - name: Build (si présent)
        run: npm run build --if-present

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build

  docker-build-and-push:
    name: Build and push Docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/elden-ring-website:latest
            ghcr.io/${{ github.repository_owner }}/elden-ring-website:${{ github.sha }}
          file: ./Dockerfile
          build-args: |
            NODE_ENV=production

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm ci
          npm run build --if-present

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
